apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-component-child-npsd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-component-child-npsd
    app.kubernetes.io/part-of: build-suite-component-update-yuzz
  name: multi-component-child-npsd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multi-component-child-npsd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multi-component-child-npsd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-fmfz-tenant/build-suite-component-update-yuzz/multi-component-child-npsd@sha256:5017f7674ed5f6bd8b0790b905c409f831104e3c88db36f8b3e8c5ca4b95f626
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
